small_fix_for_resource_list_post
AdCombo/flask-combo-jsonapi pull request #43
Opened 2021-02-18 10:41 UTC by dmitrymishanov

2021-03-15 08:44 UTC, mahenzon requested changes

2021-03-15 08:44 UTC, mahenzon commented on flask_combo_jsonapi/resource.py
> +        if result["data"] is not None and result["data"].get("links", {}).get("self"):
```suggestion
        if (result["data"] or {}).get("links", {}).get("self"):
```

2021-03-15 08:45 UTC, mahenzon commented
sorry, this comment got stuck as 'pending' and I didn't even notice it

please take a look at this suggestion

2021-03-25 07:00 UTC, dmitrymishanov commented on flask_combo_jsonapi/resource.py
> +        if result["data"] is not None and result["data"].get("links", {}).get("self"):
Yes, that's better :)

2021-04-14 11:40 UTC, merged